# Generated by Django 5.0.6 on 2024-07-22 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("miapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sanchez_tucta_persona",
            name="apellido",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="sanchez_tucta_persona",
            name="nombre",
            field=models.CharField(max_length=150),
        ),
    ]
